using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("Robert T")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.2.0.d51fbea9c47d87d7177f6aaf4face362686f33c3")]
[assembly: AssemblyTitleAttribute("pjsip4net")]
[assembly: AssemblyProductAttribute("pjsip4net")]
[assembly: AssemblyDescriptionAttribute("pjsip4net is a product of Robert T - https://github.com/amccool/pjsip4net.")]
[assembly: AssemblyTrademarkAttribute("pjsip4net - Robert T")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2015 Robert T, - Original author or authors")]

